dist: trusty

sudo: false

language: cpp php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

cache: ccache

addons:
  apt_packages:
    - libboost-all-dev
    - flex
    - bison
    - libssl-dev
    - libedit-dev
    - libyajl-dev
    - php5-cli
env:
  global:
    - ICINGAWEB_CONFIGDIR=$(pwd)/build/icingaweb2

before_script:
    - export PATH=$(pwd)/bin:${ICINGAWEB_CONFIGDIR}/bin:${PATH}
    - mkdir build
    - git clone https://github.com/Icinga/icingaweb2.git build/icingaweb2

script:
  - export PATH=$(pwd)/bin:${ICINGAWEB_CONFIGDIR}/bin:${PATH}
  - echo ${PATH}
  - cd tools/json2xml
  - make all
  - echo "{}"|./json2xml.$(uname -m).dynamic
  - echo "{}"|./json2xml.$(uname -m).static
  - cd ../..
  - build/icingaweb/bin/icingacli module list --installed

