dist: trusty

sudo: false

language: cpp

cache: ccache

addons:
  apt_packages:
    - libboost-all-dev
    - flex
    - bison
    - libssl-dev
    - libedit-dev
    - libyajl-dev

before_script:

script:
  - cd tools/json2xml
  - make all
  - echo "{}"|./json2xml.(uname -m).dynamic
  - echo "{}"|./json2xml.(uname -m).static

